---
- name: Setup users
  user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    comment: "{{ item.name }}"
    shell: /bin/bash
    group: sudo
  with_items: "{{ users }}"

- name: Add authorized keys
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.key }}"
  with_items: "{{ users }}"
