# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36e9911429907e2b742556794acd97174bac303930931241d9472cd80a1e5d19fd2115fc3925a26e485eb85c765482995381026296fda25896062813a5e24315

test:
  secret_key_base: 11041a1823c3eb3e16089aa4046ade4de5a44726e118027af52c99cbb1a5bbb1d08de7f5cb688a1b42408072c9ae936196fa68a36cd9a94ad95d985b68afbb31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
