---
- name: Add repository
  apt_repository:
    repo: ppa:nginx/development

- name: Install nginx
  apt:
    name: nginx
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Update config
  copy:
    src: nginx.conf
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx
